export const units = [
  { title: "Modern Family Unit", isUnit: true, isApartment: false, price: 350000, location: "Berlin, Germany", bedrooms: 4, bathrooms: 2, isAvailable: true },
  { title: "Cozy City Apartment", isUnit: false, isApartment: true, price: 145000, location: "Hamburg, Germany", bedrooms: 2, bathrooms: 1, isAvailable: false },
  { title: "Luxury Garden Villa", isUnit: true, isApartment: false, price: 890000, location: "Munich, Germany", bedrooms: 5, bathrooms: 3, isAvailable: true },
  { title: "Urban Studio Flat", isUnit: false, isApartment: true, price: 98000, location: "Cologne, Germany", bedrooms: 1, bathrooms: 1, isAvailable: true },
  { title: "Country Family Unit", isUnit: true, isApartment: false, price: 420000, location: "Leipzig, Germany", bedrooms: 4, bathrooms: 2, isAvailable: true },
  { title: "Riverside Apartment", isUnit: false, isApartment: true, price: 210000, location: "Dresden, Germany", bedrooms: 3, bathrooms: 1, isAvailable: false },
  { title: "PentUnit with City View", isUnit: false, isApartment: true, price: 650000, location: "Frankfurt, Germany", bedrooms: 3, bathrooms: 2, isAvailable: true },
  { title: "Budget Apartment", isUnit: false, isApartment: true, price: 78000, location: "Bremen, Germany", bedrooms: 1, bathrooms: 1, isAvailable: true },
  { title: "Historic Renovated Unit", isUnit: true, isApartment: false, price: 310000, location: "Nuremberg, Germany", bedrooms: 3, bathrooms: 2, isAvailable: false },
  { title: "Suburban Family Home", isUnit: true, isApartment: false, price: 270000, location: "Hannover, Germany", bedrooms: 3, bathrooms: 2, isAvailable: true },

  { title: "Modern Loft Apartment", isUnit: false, isApartment: true, price: 195000, location: "Stuttgart, Germany", bedrooms: 2, bathrooms: 1, isAvailable: true },
  { title: "Quiet Village Unit", isUnit: true, isApartment: false, price: 230000, location: "Kassel, Germany", bedrooms: 3, bathrooms: 1, isAvailable: true },
  { title: "Luxury Lake Unit", isUnit: true, isApartment: false, price: 920000, location: "Konstanz, Germany", bedrooms: 5, bathrooms: 3, isAvailable: true },
  { title: "Affordable Student Flat", isUnit: false, isApartment: true, price: 65000, location: "Jena, Germany", bedrooms: 1, bathrooms: 1, isAvailable: false },
  { title: "Mountain Cabin Retreat", isUnit: true, isApartment: false, price: 180000, location: "Garmisch, Germany", bedrooms: 2, bathrooms: 1, isAvailable: true },
  { title: "City Center Apartment", isUnit: false, isApartment: true, price: 260000, location: "Berlin, Germany", bedrooms: 2, bathrooms: 1, isAvailable: true },
  { title: "Large Family Villa", isUnit: true, isApartment: false, price: 780000, location: "Hamburg, Germany", bedrooms: 6, bathrooms: 3, isAvailable: false },
  { title: "Minimalist Smart Home", isUnit: true, isApartment: false, price: 410000, location: "Munich, Germany", bedrooms: 3, bathrooms: 2, isAvailable: true },
  { title: "Eco-Friendly Unit", isUnit: true, isApartment: false, price: 330000, location: "Freiburg, Germany", bedrooms: 3, bathrooms: 2, isAvailable: true },
  { title: "Old Town Apartment", isUnit: false, isApartment: true, price: 175000, location: "Bonn, Germany", bedrooms: 2, bathrooms: 1, isAvailable: true },

  { title: "Garden Duplex Home", isUnit: true, isApartment: false, price: 295000, location: "Dortmund, Germany", bedrooms: 3, bathrooms: 2, isAvailable: true },
  { title: "Modern TownUnit", isUnit: true, isApartment: false, price: 360000, location: "Essen, Germany", bedrooms: 4, bathrooms: 2, isAvailable: false },
  { title: "Studio Near University", isUnit: false, isApartment: true, price: 85000, location: "Münster, Germany", bedrooms: 1, bathrooms: 1, isAvailable: true },
  { title: "Luxury PentUnit Suite", isUnit: false, isApartment: true, price: 720000, location: "Düsseldorf, Germany", bedrooms: 4, bathrooms: 3, isAvailable: true },
  { title: "Quiet Suburban Unit", isUnit: true, isApartment: false, price: 250000, location: "Aachen, Germany", bedrooms: 3, bathrooms: 1, isAvailable: true },
  { title: "Modern Apartment", isUnit: false, isApartment: true, price: 210000, location: "Karlsruhe, Germany", bedrooms: 2, bathrooms: 1, isAvailable: false },
  { title: "Country Cottage", isUnit: true, isApartment: false, price: 160000, location: "Weimar, Germany", bedrooms: 2, bathrooms: 1, isAvailable: true },
  { title: "Lakefront Apartment", isUnit: false, isApartment: true, price: 240000, location: "Potsdam, Germany", bedrooms: 2, bathrooms: 1, isAvailable: true },
  { title: "Renovated Loft", isUnit: false, isApartment: true, price: 310000, location: "Leipzig, Germany", bedrooms: 3, bathrooms: 2, isAvailable: true },
  { title: "Budget-Friendly Flat", isUnit: false, isApartment: true, price: 70000, location: "Chemnitz, Germany", bedrooms: 1, bathrooms: 1, isAvailable: true },

  { title: "Luxury Mansion Estate", isUnit: true, isApartment: false, price: 1500000, location: "Berlin, Germany", bedrooms: 8, bathrooms: 5, isAvailable: false },
  { title: "Small Family Unit", isUnit: true, isApartment: false, price: 210000, location: "Hannover, Germany", bedrooms: 3, bathrooms: 1, isAvailable: true },
  { title: "Modern Smart Apartment", isUnit: false, isApartment: true, price: 190000, location: "Stuttgart, Germany", bedrooms: 2, bathrooms: 1, isAvailable: true },
  { title: "Village FarmUnit", isUnit: true, isApartment: false, price: 280000, location: "Kiel, Germany", bedrooms: 4, bathrooms: 2, isAvailable: true },
  { title: "City View Apartment", isUnit: false, isApartment: true, price: 230000, location: "Frankfurt, Germany", bedrooms: 2, bathrooms: 1, isAvailable: false },
  { title: "Renovated Duplex", isUnit: true, isApartment: false, price: 260000, location: "Bremen, Germany", bedrooms: 3, bathrooms: 2, isAvailable: true },
  { title: "Luxury Garden Villa", isUnit: true, isApartment: false, price: 980000, location: "Munich, Germany", bedrooms: 6, bathrooms: 4, isAvailable: true },
  { title: "Affordable Studio", isUnit: false, isApartment: true, price: 60000, location: "Jena, Germany", bedrooms: 1, bathrooms: 1, isAvailable: true },
  { title: "Mountain View Unit", isUnit: true, isApartment: false, price: 320000, location: "Garmisch, Germany", bedrooms: 3, bathrooms: 2, isAvailable: false },
  { title: "Urban Apartment", isUnit: false, isApartment: true, price: 180000, location: "Berlin, Germany", bedrooms: 2, bathrooms: 1, isAvailable: true },

  { title: "Quiet Forest Cabin", isUnit: true, isApartment: false, price: 140000, location: "Black Forest, Germany", bedrooms: 2, bathrooms: 1, isAvailable: true },
  { title: "Modern City Loft", isUnit: false, isApartment: true, price: 220000, location: "Hamburg, Germany", bedrooms: 2, bathrooms: 1, isAvailable: true },
  { title: "Large Suburban Villa", isUnit: true, isApartment: false, price: 540000, location: "Cologne, Germany", bedrooms: 5, bathrooms: 3, isAvailable: false },
  { title: "Budget Apartment", isUnit: false, isApartment: true, price: 68000, location: "Dresden, Germany", bedrooms: 1, bathrooms: 1, isAvailable: true },
  { title: "Lake Unit Cabin", isUnit: true, isApartment: false, price: 210000, location: "Konstanz, Germany", bedrooms: 2, bathrooms: 1, isAvailable: true },
  { title: "Renovated City Flat", isUnit: false, isApartment: true, price: 195000, location: "Bonn, Germany", bedrooms: 2, bathrooms: 1, isAvailable: true },
  { title: "Modern Duplex Home", isUnit: true, isApartment: false, price: 310000, location: "Dortmund, Germany", bedrooms: 3, bathrooms: 2, isAvailable: true },
  { title: "Luxury Smart Villa", isUnit: true, isApartment: false, price: 850000, location: "Düsseldorf, Germany", bedrooms: 5, bathrooms: 3, isAvailable: true },
  { title: "Small Apartment", isUnit: false, isApartment: true, price: 90000, location: "Aachen, Germany", bedrooms: 1, bathrooms: 1, isAvailable: false },
  { title: "Modern Family Home", isUnit: true, isApartment: false, price: 330000, location: "Karlsruhe, Germany", bedrooms: 4, bathrooms: 2, isAvailable: true },

  { title: "Country Unit", isUnit: true, isApartment: false, price: 240000, location: "Weimar, Germany", bedrooms: 3, bathrooms: 1, isAvailable: true },
  { title: "Lakefront Villa", isUnit: true, isApartment: false, price: 760000, location: "Potsdam, Germany", bedrooms: 5, bathrooms: 3, isAvailable: false },
  { title: "Urban Smart Apartment", isUnit: false, isApartment: true, price: 210000, location: "Leipzig, Germany", bedrooms: 2, bathrooms: 1, isAvailable: true },
  { title: "Budget Studio Flat", isUnit: false, isApartment: true, price: 55000, location: "Chemnitz, Germany", bedrooms: 1, bathrooms: 1, isAvailable: true },
  { title: "Luxury Mansion Estate", isUnit: true, isApartment: false, price: 1800000, location: "Berlin, Germany", bedrooms: 10, bathrooms: 6, isAvailable: false },
  { title: "Small TownUnit", isUnit: true, isApartment: false, price: 200000, location: "Hannover, Germany", bedrooms: 3, bathrooms: 1, isAvailable: true },
  { title: "Modern Apartment Loft", isUnit: false, isApartment: true, price: 185000, location: "Stuttgart, Germany", bedrooms: 2, bathrooms: 1, isAvailable: true },
  { title: "Village Unit", isUnit: true, isApartment: false, price: 260000, location: "Kiel, Germany", bedrooms: 4, bathrooms: 2, isAvailable: true },
  { title: "City Apartment", isUnit: false, isApartment: true, price: 225000, location: "Frankfurt, Germany", bedrooms: 2, bathrooms: 1, isAvailable: false },
  { title: "Renovated Duplex Home", isUnit: true, isApartment: false, price: 280000, location: "Bremen, Germany", bedrooms: 3, bathrooms: 2, isAvailable: true }
];
